name: build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
#  build-macos:
#    runs-on: macos-11
#    steps:
#    - uses: actions/checkout@v2
#    # reads .swift-version
#    - uses: YOCKOW/Action-setup-swift@v1.1.14
#    - run:  | 
#        brew install kylef/formulae/swiftenv
#        echo 'if which swiftenv > /dev/null; then eval "$(swiftenv init -)"; fi' >> ~/.bash_profile
#        swiftenv install 
#        swift build
    build-linux:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                swift:  [5.5.3]
        env: 
            swift-toolchain-file:   $GITHUB_WORKSPACE/swift-${{ matrix.swift }}.tar.gz
        steps:
            -   uses: actions/checkout@v2
            
            -   name: cache swift toolchains
                uses: actions/cache@v2
                with:
                    path: ${{ env.swift-toolchain-file }}
                    key: ${{ runner.os }}:swift:${{ matrix.swift }}
                    
            -   name: cache status
                id:   cache_status
                uses: andstor/file-existence-action@v1
                with:
                    files: ${{ env.swift-toolchain-file }}
            
            -   name: download swift toolchain 
                if: steps.cache_status.outputs.files_exists == 'false'
                run: curl https://download.swift.org/swift-${{ matrix.swift }}-release/ubuntu2004/swift-${{ matrix.swift }}-RELEASE/swift-${{ matrix.swift }}-RELEASE-ubuntu20.04.tar.gz --output ${{ env.swift-toolchain-file }}
            
            -   name: set up swift
                run: |
                    mkdir -p $GITHUB_WORKSPACE/swift-${{ matrix.swift }}
                    tar -xzf ${{ env.swift-toolchain-file }} -C $GITHUB_WORKSPACE/swift-${{ matrix.swift }} --strip 1
                    echo "$GITHUB_WORKSPACE/swift-${{ matrix.swift }}/usr/bin" >> $GITHUB_PATH

            -   name: build 
                run: |
                    swift --version
                    swift build
